# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_nb": "00_core.ipynb",
         "nb_iter": "00_core.ipynb",
         "code_iter": "00_core.ipynb",
         "extract_code": "00_core.ipynb",
         "build_all": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://omlnaut.github.io/nb_export/"

git_url = "https://github.com/omlnaut/nb_export/tree/master/"

def custom_doc_links(name): return None
