# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://omlnaut.github.io/nb_export/"

git_url = "https://github.com/omlnaut/nb_export/tree/master/"

def custom_doc_links(name): return None
